name: Push Docker Images

on:
  push:
    branches:
      - master
jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t edx
  
  buildx:
    env:
      DOCKER_BUILDKIT: '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t edx

  buildx_cache_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: edx
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  buildx_with_local_registry:
    env:
      DOCKER_BUILDKIT: '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-docker
        uses: actions/cache@v2
        with:
          path: /tmp/docker-registry
          key: docker-registry-buildkit-${{ github.sha }}
      - run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2 && npx wait-on tcp:5000
      - run: docker build . -t thing --cache-from=localhost:5000/thing --build-arg BUILDKIT_INLINE_CACHE=1
      - run: docker tag thing localhost:5000/thing && docker push localhost:5000/thing || true
        if: steps.cache.outputs.cache-hit != 'true'
  
  build_with_docker_registry-cache:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: github-actions-benchmark/edx-platform:latest
          cache-from: type=registry,ref=github-actions-benchmark/edx-platform:latest
          cache-to: type=inline